# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68b049df6ca4607be89f62c107c8c8ac145bf9ffafcf787d7810b9023b7ef47f352dcef1cc211cccf478a8bdc77cdd77fa3293c5c7d69691b81acbec95a21a38

test:
  secret_key_base: 4426198932820d5243e2acd05f09182befacbbe163fce1959a369e0b81d223de1098890303c5eb271294ef70b241cc4f197f9f20140a911239f18ea5aaa213d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
